lsi: false
safe: true
source: .
incremental: false
highlighter: blue
future: true
gist:
  noscript: false
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: blue
title: Avancement TIPE
show_dir_listing: false
description: Un site pour suivre mes avancées sur le TIPE 2025-26.
lang: fr_FR
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
