lsi: false
safe: true
source: .
incremental: false
future: true
highlight: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  math_engine: mathjax
title: Avancement TIPE
show_dir_listing: false
description: Un site pour suivre mes avancées sur le TIPE 2025-26.
lang: fr_FR
exclude: 
- gemset.nix
- shell.nix
remote_theme: pages-themes/cayman@v0.2.0

toc:
  max_level: 3

defaults:
  - scope:
      path: ""
    values: 
      toc: true

scholar:
  style: apa
  locale: fr

plugins:
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-default-layout
- jekyll-optional-front-matter
- jekyll-title-from-headings
- jekyll-toc
- jekyll-microtypo
- jekyll-scholar
