lsi: false
safe: true
source: .
incremental: false
highlighter: blue
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: blue
title: Avancement TIPE
description: Un site pour suivre mes avancées sur le TIPE 2024-25.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
